"""The game-rules layer.

`config/buildings.yaml` is the single source of truth for what may exist at a given
Town Hall level, how many, and up to what level. The generator reads caps from here
and has no other way to decide counts, so a building that is not unlocked at a TH
cannot be placed there -- that is a structural property, not a check someone
remembered to write.

The file is generated by `tools/import_game_data.py` from published upstream game
data. `Catalog.load` re-validates it on every load, so a bad regeneration fails at
startup rather than quietly producing a poisoned dataset.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import yaml

from .schema import HEADINGS

DEFAULT_CONFIG = Path(__file__).resolve().parent.parent / "config" / "buildings.yaml"

#: Placement never fills more than this fraction of the grid, so a catalog whose
#: rosters cannot physically fit is caught at load time instead of as thin bases.
MAX_GRID_FILL = 0.80


class CatalogError(ValueError):
    """Raised when buildings.yaml is internally inconsistent."""


@dataclass(frozen=True)
class ThRule:
    """What a single building type is allowed to do at one Town Hall level."""

    count: int
    max_level: int


@dataclass(frozen=True)
class BuildingDef:
    """A building type and its per-Town-Hall rules."""

    id: str
    display_name: str
    category: str
    footprint: tuple[int, int]
    directions: int
    per_th: dict[int, ThRule]

    @property
    def area(self) -> int:
        """Tiles consumed by one instance."""
        return self.footprint[0] * self.footprint[1]

    @property
    def is_directional(self) -> bool:
        return self.directions > 1

    @property
    def min_th(self) -> int:
        return min(self.per_th)

    def rule(self, th: int) -> ThRule | None:
        """Rules at `th`, or None if this building is not unlocked there."""
        return self.per_th.get(th)


class Catalog:
    """Loaded, validated building rules."""

    def __init__(self, buildings: dict[str, BuildingDef], grid_tiles: int, max_town_hall: int):
        self.buildings = buildings
        self.grid_tiles = grid_tiles
        self.max_town_hall = max_town_hall

    # ---- loading ---------------------------------------------------------

    @classmethod
    def load(cls, path: Path | str = DEFAULT_CONFIG) -> Catalog:
        raw = yaml.safe_load(Path(path).read_text(encoding="utf-8"))
        buildings = {}
        for bid, spec in (raw.get("buildings") or {}).items():
            fp = spec["footprint"]
            buildings[bid] = BuildingDef(
                id=bid,
                display_name=spec.get("display_name", bid),
                category=spec.get("category", "other"),
                footprint=(int(fp[0]), int(fp[1])),
                directions=int(spec.get("directions", 1)),
                per_th={
                    int(th): ThRule(int(v["count"]), int(v["max_level"]))
                    for th, v in (spec.get("per_th") or {}).items()
                },
            )
        cat = cls(buildings, int(raw["grid_tiles"]), int(raw["max_town_hall"]))
        cat.validate()
        return cat

    # ---- queries ---------------------------------------------------------

    def __getitem__(self, bid: str) -> BuildingDef:
        return self.buildings[bid]

    def __contains__(self, bid: str) -> bool:
        return bid in self.buildings

    @property
    def type_names(self) -> list[str]:
        """Stable sorted type list. Index in this list is the YOLO class id, so it
        must not depend on dict or file ordering."""
        return sorted(self.buildings)

    def class_index(self) -> dict[str, int]:
        return {t: i for i, t in enumerate(self.type_names)}

    def roster(self, th: int) -> list[BuildingDef]:
        """Every building type unlocked at `th`, in stable order."""
        self._check_th(th)
        return [self.buildings[t] for t in self.type_names if th in self.buildings[t].per_th]

    def rule(self, bid: str, th: int) -> ThRule | None:
        return self.buildings[bid].rule(th)

    def roster_area(self, th: int) -> int:
        """Tiles consumed if every unlocked building is built to its cap."""
        return sum(b.area * b.per_th[th].count for b in self.roster(th))

    def _check_th(self, th: int) -> None:
        if not 1 <= th <= self.max_town_hall:
            raise ValueError(f"Town Hall {th} outside catalog range 1..{self.max_town_hall}")

    # ---- validation ------------------------------------------------------

    def validate(self) -> None:
        """Assert the catalog is internally coherent. Raises CatalogError."""
        problems: list[str] = []

        if self.grid_tiles <= 0:
            problems.append(f"grid_tiles must be positive, got {self.grid_tiles}")
        if not self.buildings:
            problems.append("catalog contains no buildings")

        for b in self.buildings.values():
            if b.footprint[0] <= 0 or b.footprint[1] <= 0:
                problems.append(f"{b.id}: footprint must be positive, got {b.footprint}")
            if b.footprint[0] > self.grid_tiles or b.footprint[1] > self.grid_tiles:
                problems.append(f"{b.id}: footprint {b.footprint} exceeds {self.grid_tiles}-tile grid")
            if b.directions < 1:
                problems.append(f"{b.id}: directions must be >= 1, got {b.directions}")
            if b.directions > 1 and len(HEADINGS) % b.directions:
                problems.append(
                    f"{b.id}: directions={b.directions} must divide {len(HEADINGS)} "
                    "so every facing lands on a compass heading"
                )
            if not b.per_th:
                problems.append(f"{b.id}: unlocked at no Town Hall level")
                continue

            ths = sorted(b.per_th)
            if ths[0] < 1 or ths[-1] > self.max_town_hall:
                problems.append(f"{b.id}: TH range {ths[0]}..{ths[-1]} outside 1..{self.max_town_hall}")
            # Once unlocked, a building never disappears again.
            if ths != list(range(ths[0], ths[0] + len(ths))):
                problems.append(f"{b.id}: TH range has gaps: {ths}")
            if ths[-1] != self.max_town_hall:
                problems.append(f"{b.id}: unlocked at TH{ths[0]} but missing at TH{self.max_town_hall}")

            # A real unlock table never regresses.
            for prev, cur in zip(ths, ths[1:]):
                if b.per_th[cur].count < b.per_th[prev].count:
                    problems.append(
                        f"{b.id}: count drops from {b.per_th[prev].count} at TH{prev} "
                        f"to {b.per_th[cur].count} at TH{cur}"
                    )
                if b.per_th[cur].max_level < b.per_th[prev].max_level:
                    problems.append(
                        f"{b.id}: max_level drops from {b.per_th[prev].max_level} at TH{prev} "
                        f"to {b.per_th[cur].max_level} at TH{cur}"
                    )
            for th, rule in b.per_th.items():
                if rule.count < 1:
                    problems.append(f"{b.id}: TH{th} count must be >= 1 if listed, got {rule.count}")
                if rule.max_level < 1:
                    problems.append(f"{b.id}: TH{th} max_level must be >= 1, got {rule.max_level}")

        # Every roster must physically fit, with room for placement to succeed.
        capacity = self.grid_tiles**2
        for th in range(1, self.max_town_hall + 1):
            try:
                used = self.roster_area(th)
            except KeyError:
                continue
            if used > capacity * MAX_GRID_FILL:
                problems.append(
                    f"TH{th}: roster needs {used} tiles, over {MAX_GRID_FILL:.0%} "
                    f"of the {capacity}-tile grid"
                )

        if problems:
            raise CatalogError(
                "config/buildings.yaml is inconsistent:\n  - " + "\n  - ".join(problems)
            )
