"""YOLO export, derived from the canonical label JSON.

Class ids come from the catalog's sorted type list, committed alongside the dataset,
so adding a building type later cannot silently renumber an existing dataset.

Rotation has no slot in a YOLO box, so there are two modes:

* ``ignore``  -- one class per building type; facing stays in the JSON, which is
  where a real training loop reads it from anyway.
* ``split``   -- directional types expand to one class per facing
  (``air_sweeper_dir0`` ... ``air_sweeper_dir7``), turning orientation into a
  classification the detector has to get right.
"""
from __future__ import annotations

from pathlib import Path

from .catalog import Catalog
from .labels import read_label
from .schema import BaseLabel

DirectionMode = str  # "ignore" | "split"


def class_names(catalog: Catalog, direction_mode: DirectionMode = "ignore") -> list[str]:
    """Stable class list. Index in this list is the YOLO class id."""
    if direction_mode == "ignore":
        return catalog.type_names
    if direction_mode == "split":
        names: list[str] = []
        for t in catalog.type_names:
            b = catalog[t]
            names += [f"{t}_dir{d}" for d in range(b.directions)] if b.is_directional else [t]
        return names
    raise ValueError(f"unknown direction_mode {direction_mode!r}")


def class_of(label_type: str, direction: int, index: dict[str, int], direction_mode: DirectionMode) -> int:
    key = f"{label_type}_dir{direction}" if direction_mode == "split" and f"{label_type}_dir{direction}" in index else label_type
    return index[key]


def label_to_lines(
    label: BaseLabel,
    index: dict[str, int],
    direction_mode: DirectionMode = "ignore",
    min_visibility: float = 0.0,
) -> list[str]:
    """One `class cx cy w h` line per visible building, normalised to image size."""
    iw, ih = label.image_size
    lines: list[str] = []
    for b in label.buildings:
        if b.visibility < min_visibility:
            continue
        x, y, w, h = b.bbox_px
        cx, cy = (x + w / 2) / iw, (y + h / 2) / ih
        lines.append(
            f"{class_of(b.type, b.direction, index, direction_mode)} "
            f"{cx:.6f} {cy:.6f} {w / iw:.6f} {h / ih:.6f}"
        )
    return lines


def line_to_bbox(line: str, image_size: tuple[int, int]) -> tuple[int, tuple[float, float, float, float]]:
    """Inverse of `label_to_lines`, for round-trip verification."""
    parts = line.split()
    cls = int(parts[0])
    cx, cy, w, h = (float(v) for v in parts[1:5])
    iw, ih = image_size
    return cls, ((cx - w / 2) * iw, (cy - h / 2) * ih, w * iw, h * ih)


def export(
    out_dir: Path,
    catalog: Catalog,
    direction_mode: DirectionMode = "ignore",
    min_visibility: float = 0.0,
) -> dict[str, int]:
    """Convert every label JSON under `out_dir/labels` into `out_dir/yolo`."""
    out_dir = Path(out_dir)
    label_dir = out_dir / "labels"
    yolo_dir = out_dir / "yolo"
    (yolo_dir / "labels").mkdir(parents=True, exist_ok=True)

    names = class_names(catalog, direction_mode)
    index = {n: i for i, n in enumerate(names)}

    files = boxes = 0
    for path in sorted(label_dir.glob("*.json")):
        label = read_label(path)
        lines = label_to_lines(label, index, direction_mode, min_visibility)
        (yolo_dir / "labels" / f"{path.stem}.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")
        files += 1
        boxes += len(lines)

    names_block = "\n".join(f"  {i}: {n}" for i, n in enumerate(names))
    (yolo_dir / "data.yaml").write_text(
        "# Generated by cocsynth.export_yolo -- do not edit by hand.\n"
        f"# direction_mode: {direction_mode}\n"
        f"path: {out_dir.resolve()}\n"
        "train: images\n"
        "val: images\n"
        f"nc: {len(names)}\n"
        "names:\n" + names_block + "\n",
        encoding="utf-8",
    )
    return {"files": files, "boxes": boxes, "classes": len(names)}
